### PR TITLE
add body font-size changer

### PR DESCRIPTION
**Pull request by LordSimal**
Redo #961 with `9.2` as a base branch

### CODE REVIEW

**Comment by LordSimal** [comment]
I gotta say: Making those tests work is quite cumbersome...

**Comment by sebastianbergmann** [comment]
I will look into the `preg_match(): Compilation failed: regular expression is too large` issue.

**Comment by sebastianbergmann** [comment]
I do not have a solution for the `preg_match()` issue yet, but this is needed:
```patch
diff --git a/tests/_files/Report/HTML/PHP81AndUp/CoverageForClassWithAnonymousFunction/index.html b/tests/_files/Report/HTML/PHP81AndUp/CoverageForClassWithAnonymousFunction/index.html
index 6651a25..abd2702 100644
--- a/tests/_files/Report/HTML/PHP81AndUp/CoverageForClassWithAnonymousFunction/index.html
+++ b/tests/_files/Report/HTML/PHP81AndUp/CoverageForClassWithAnonymousFunction/index.html
@@ -122,6 +122,5 @@
   </div>
   <script src="_js/jquery.min.js" type="text/javascript"></script>
   <script src="_js/font-size-changer.js" type="text/javascript"></script>
-  <script src="_js/font-size-changer.js" type="text/javascript"></script>
  </body>
 </html>
```

**Comment by LordSimal** [comment]
Right, i missed that one

**Comment by LordSimal** [comment]
just wanted to ask if you found a solution for the `preg_match()` error 😄

**Comment by sebastianbergmann** [comment]
Thank you for your contribution. I appreciate the time you invested in preparing this pull request. However, I have decided not to merge it as I think that using the browser's native zoom functionality is a better fit.

**Comment by JoSSte** [comment]
@sebastianbergmann having to zoom every single page you visit, while analyzing logs is actually quite tedious. I came here so report this issue, found #961  and was pleased. Followed this thread and am dissapointed. Could it be possible to change the default size to a unit based off the window size like `vw` or `vh` instead of `em` which is basedd off of the screen size? 
https://www.w3.org/Style/Examples/007/units.en.html

**Comment by sebastianbergmann** [comment]
As I wrote in https://github.com/sebastianbergmann/php-code-coverage/issues/960#issuecomment-1321047159

> I am not a frontend developer, sorry.

If you think that using `vw` or `vh` would fix this: great. Send a pull request so that others can provide feedback.

**Pull request closed without merging**
