### PR TITLE
date() expects parameter 2 to be a integer but it get a string on php7

### PR DESCRIPTION
**Pull request by prisis**

### CODE REVIEW

**Comment by prisis** [comment]
@sebastianbergmann should i, fix the xdebug error on night php in travis?

**Comment by GrahamCampbell** [comment]
Xdebug doesn't support php 7.1.

**Comment by prisis** [comment]
then add it to allow_failures?

**Comment by GinoPane** [comment]
> Xdebug doesn't support php 7.1.

from the official website:

> [2016-01-25] - Xdebug 2.4.0RC4 is out!
> This is the fourth and hopefully last release candidate of the 2.4 series. The 2.4 series adds support for PHP 7 and is in large parts a rewrite of the earlier code base to support PHP 5.4 through PHP 7.0. This release candidate fixes among others, a bunch of crashes, **and adds support for PHP 7.1.**

**Comment by prisis** [comment]
@sebastianbergmann should i update this pr or close it?

**Pull request closed without merging**
