### PR TITLE
Line coverage of methods should reflect actual coverage

### PR DESCRIPTION
**Pull request by bastien-phi**
Corrects line coverage of methods in Cobertura report.

### CODE REVIEW

**Comment by bastien-phi** [comment]
It looks like decreasing number of lines in `Cobertura.php` also decreases global coverage. Do I need to do something else ?

**Comment by sebastianbergmann** [comment]
CC @smmccabe

**Comment by smmccabe** [comment]
This PR looks good to me, when i tested with gitlab it only reads the stand-alone line reports, not the ones within methods so it wasn't relevant to me. I doubled checked some sample examples and @bastien-phi fix is correct. I based my initial work off of clover which doesn't duplicate the lines, which was incorrect.

tl;dr  - looks good to merge in, thnx @bastien-phi

**Comment by sebastianbergmann** [comment]
Thank you for the review, @smmccabe.

**Pull request merged**
