### PR TITLE
GH-1037 - CSS fixes for first column of code review table.

### PR DESCRIPTION
**Pull request by gammamatrix**
## Changes
- I did a quick test and it appears to work fine in Chrome and Firefox, but the selector does not appear to work on old Safari.

### CODE REVIEW

**Comment by gammamatrix** [comment]
## Changes

```css
table#code td:first-of-type {
  padding-left: .75em;
  padding-right: .75em;
}

table#code td:first-of-type a {
  text-decoration: none;
}
```
- This appears to be working on Chrome, Firefox and Safari.
- Did I cover the padding in the right spot?

**Comment by sebastianbergmann** [comment]
I still see the whitespace after this PR on Firefox 130 and Chrome 128:

grafik

**Comment by gammamatrix** [comment]
Is that extra space just from the flex box and making the view port over 2000px?

I did a comparison... I marked the images, the two in the middle are for Firefox 130 with Bootstrap 5 on the left and Bootstrap 4 on the right.
- The outside browsers are both Chrome:

GH-1046-chrome-128-firefox-130-with-bootstrap-4-and-5

**Comment by sebastianbergmann** [comment]
> Is that extra space just from the flex box and making the view port over 2000px?

Maybe. I always have my browser windows full-screen :)

**Pull request merged**
