### PR TITLE
Put the columns in all reports in a consistent order for #827

### PR DESCRIPTION
**Pull request by CJDennis**

### CODE REVIEW

**Comment by CJDennis** [comment]
@sebastianbergmann Can you review this change please? The only issue is decreased coverage in `private function unionOrIntersectionAsString(ComplexType $type)`, but that method didn't even exist when I made my changes.

**Comment by sebastianbergmann** [comment]
I will review this as soon as I find the time. In the meantime, please make sure that there are no coding guidelines violations.

**Comment by CJDennis** [comment]
I thought I'd check the progress of this pull request (because the code coverage reports still have the columns in the wrong order) and I saw some of the automated tests had glitches. I ran friendsofphp/php-cs-fixer manually and it changed no files. There seems to be no way to rerun the tests to clear false negatives.

Is it usual for pull requests to take so long to be reviewed? Is it not being reviewed because of the false negatives? What is the procedure to clear false negatives?

**Comment by sebastianbergmann** [comment]
I did not have time to look at this yet, sorry.

**Comment by sebastianbergmann** [comment]
I wanted to review this just now, but now the PR has conflicts that must be resolved. I am sorry it took so long for me to look into this. Can you please rebase your work? Thanks!

**Comment by sebastianbergmann** [comment]
Superseded by #900.

**Pull request closed without merging**
