### PR TITLE
Throw: mark as executable expression line regardless of type

### PR DESCRIPTION
**Pull request by Slamdunk**
Fix bug found in https://github.com/infection/infection/issues/1778

### CODE REVIEW

**Comment by romm** [comment]
I can confirm the fix works, thanks @Slamdunk!

**Comment by Slamdunk** [comment]
@sebastianbergmann may I ask you a release for this please? That would be very welcome 🙏

**Comment by sebastianbergmann** [comment]
> @sebastianbergmann may I ask you a release for this please?

Done.

**Comment by Slamdunk** [comment]
Thank you very much

**Pull request merged**
