### PR TITLE
Compile uncovered files with opcache

### PR DESCRIPTION
**Pull request by mvorisek**
Uncovered executable lines must match executable lines from real coverage drivers. This was discovered to be not easy in https://github.com/sebastianbergmann/php-code-coverage/pull/938.

This is problematic and it seems `opcache_compile_file` is a solution. It very nicely collects all possible coverage points (with zero coverage of course).

~In next major version, we can even remove the `processUncoveredFiles` option.~ (already removed)

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
I am reluctant to merge a change such as this into a minor version, even more so since it addresses an issue that no longer exists in `main`.

**Comment by mvorisek** [comment]
> I am reluctant to merge a change such as this into a minor version, even more so since it addresses an issue that no longer exists in `main`.

@sebastianbergmann looking into the 10.0.0 changelog, you mean https://github.com/sebastianbergmann/php-code-coverage/issues/856?

Such PR removes `processUncoveredFiles` (good), but does not solve the problem of different uncovered lines when not compiled (or executed). Related with https://github.com/sebastianbergmann/phpcov/issues/122, we are experiencing about 0.5% coverage difference... Took me long hours to figure this problem out.

**Comment by mvorisek** [comment]
In https://github.com/atk4/ui/pull/1852 this change increased our coverage by almost 1% because of https://github.com/sebastianbergmann/php-code-coverage/issues/942

**Comment by mvorisek** [comment]
closing as this solution requires opcache and not yet compiled file, closing in favor of fully fixed executable lines static analyser, most fixes landed in https://github.com/sebastianbergmann/php-code-coverage/pull/949

**Pull request closed without merging**
