### PR TITLE
Add sorting capability to HTML render

### PR DESCRIPTION
**Pull request by fezfez**
Hi,

I have added a sorting capability to HTML render in directory view.

Thanks for you work.

### CODE REVIEW

**Comment by fezfez** [comment]
Any news on this PR ? :smiley:

**Comment by fezfez** [comment]
Any chance to be merge ? :beers:

**Comment by sebastianbergmann** [comment]
Sorry, but I am not convinced that this is useful.

**Comment by fezfez** [comment]
So close

**Pull request closed without merging**
