### PR TITLE
Upgraded bootstrap, jquery and popper

### PR DESCRIPTION
**Pull request by GrahamCampbell**
* Bootstrap 4.3.1 (https://github.com/twbs/bootstrap/releases/download/v4.3.1/bootstrap-4.3.1-dist.zip)
* jQuery 3.4.1 (https://code.jquery.com/jquery-3.4.1.min.js)
* popper 1.15.0 (https://raw.githubusercontent.com/FezVrasta/popper.js/v1.15.0/dist/popper.min.js)

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
With this patch the popin for "which line covers this test" no longer works.

**Comment by GrahamCampbell** [comment]
Whoops. Give me a sec to double check which version we upgraded from, so I can see what's changed upstream to cause this.

**Comment by GrahamCampbell** [comment]
image

**Comment by GrahamCampbell** [comment]
Well, they claim to have made no breaking changes between 1.14.3 and 1.15.0... https://github.com/FezVrasta/popper.js/releases

**Comment by sebastianbergmann** [comment]
Updating [Bootstrap to 4.3.1](https://github.com/sebastianbergmann/php-code-coverage/commit/cfc7f556bef3458d4b052c76579c376bc4b96205) and [jQuery to 3.4.1](https://github.com/sebastianbergmann/php-code-coverage/commit/0e6ad854dc76bd6751e3b3b15aa78e6b8605996f) does not break the popin. It is the update to popper 1.15.0 that does.

**Comment by DanielRuf** [comment]
Hi @GrahamCampbell,

your PR uses the ESM version which does not work in this setup.

image

image


The UMD version does work.
https://unpkg.com/popper.js@1.15.0/dist/umd/popper.min.js

image

Can you replace it?

**Comment by sebastianbergmann** [comment]
Thank you, @DanielRuf, I have updated popper.js in d0f4b079fb023c6ef969b857529188a316293911.

**Comment by GrahamCampbell** [comment]
Great.

**Pull request closed without merging**
