### PR TITLE
update from master

### PR DESCRIPTION
**Pull request by posey2010**
i would like to dev the path coverage feature, please merge from master

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
?

**Comment by posey2010** [comment]
path-coverage branch stopped commit at July of 2015

**Comment by Maks3w** [comment]
This is already done by #400

**Comment by posey2010** [comment]
@Maks3w  cool. @sebastianbergmann do you have plan to review #400 ?

**Comment by posey2010** [comment]
@Maks3w 
If i want to use your version about path coverage, which one should i choose? #400 , #401  or merge them? thanks

**Comment by Maks3w** [comment]
Any of them. #401 is on top of #400

**Comment by posey2010** [comment]
Got it, thank you. I will try it. @Maks3w

**Comment by sebastianbergmann** [comment]
Closing #400 and #425 because they have run out-of-sync with `master`. Please coordinate, @Maks3w and @posey2010, and send a new pull request. Thanks!

**Pull request closed without merging**
