### PR TITLE
Fix count(): Parameter must be an array or an object that implements …

### PR DESCRIPTION
**Pull request by remicollet**
…Countable

As `$coverageData[$i]` can be NULL (tested below)

### CODE REVIEW

**Comment by sebastianbergmann** [comment]
Do you have a reproducing test case that triggers this? I'd rather fix a root cause than a symptom.

**Comment by remicollet** [comment]
From Fedora QA since PHP 7.2.0RC5
https://apps.fedoraproject.org/koschei/package/php-phpunit-php-code-coverage5?collection=f28

```
There was 1 error:
1) SebastianBergmann\CodeCoverage\Report\Html\HTMLTest::testForBankAccountTest
count(): Parameter must be an array or an object that implements Countable
/builddir/build/BUILD/php-code-coverage-8ed1902a57849e117b5651fc1a5c48110946c06b/tests/tests/HTMLTest.php:47
```

Other failure are the same that travis reports.

As you have  `if ($coverageData[$i] === null) { ` I think null is a valid value, but is not coutable in PHP 7.2

**Comment by remicollet** [comment]
> Do you have a reproducing test case that triggers this?

Yes, the test suite included in this repo ;)

**Comment by sebastianbergmann** [comment]
Thanks.

**Pull request merged**
