### PR TITLE
Add option to ignore covers annotation

### PR DESCRIPTION
**Pull request by BackEndTea**
This PR:

* Adds the option to ignore coverage annotations, as mentioned in #571 
 
If preferred, i can also make a PR against v5.3 instead

### CODE REVIEW

**Comment by biganfa** [comment]
@BackEndTea why it was closed and not merged? Souds useful. Corresponding stackoverflow question [here](https://stackoverflow.com/questions/48493131/generate-phpunit-code-coverage-while-ignoring-covers/55918286#55918286).

**Comment by JeroenDeDauw** [comment]
Yes, this would be very useful. Right now I can't use the coverage report in several of my projects without either removing the @covers tags or adding a whole lot that I think are better not added.

**Comment by JeroenDeDauw** [comment]
Presumably this was closed because it sat here for one and a half year without any review, even though only a few lines where changed.

**Comment by kubawerlos** [comment]
> Right now I can't use the coverage report

@JeroenDeDauw but you can - the whole point of `@covers*` annotations is to make coverage report more meaningful.

> without either removing the **@Covers** tags or adding a whole lot

I don't understand what's your problem - you can run the PHPUnit with only some test classes having the `@covers*` annotations.

**Comment by JeroenDeDauw** [comment]
@kubawerlos are you saying I can literally add `@covers*` to an integration test to have PHPUnit mark all code it executes as covered?

**Comment by kubawerlos** [comment]
No, I'm saying one way or another - benefit from `@covers*` annotations to know what was intentionally covered or remove them to cover all executed code.

What what you writing I understood you have the annotations, but sometimes you don't want to use them - that's what confuses me - what is the reason of the inconsistency?

**Comment by JeroenDeDauw** [comment]
When you follow something like the clean architecture, you end up with a bunch of use cases that hold application logic and typically each have a request model and a response model. These two model objects are simple DTOs and are not worth unit testing. There are other classes not worth unit testing. The integration tests for the use cases only have one covers tag: for the use case. They do not have a long list of all these other classes, which I think they should not be required to have. So even though my whole application is tested on a sensible level, code coverage shows (incorrectly) low, and is not usable for finding code that is not tested.

Example codebase: https://github.com/wmde/fundraising-donations

**Comment by fkupper** [comment]
Can't you just whitelist/blacklist what you want?

**Comment by JeroenDeDauw** [comment]
That would require many entries and create maintenance overhead. All in all, less preferred than not having the coverage work at all.

**Pull request closed without merging**
