### PR TITLE
Added no-cache metatags

### PR DESCRIPTION
**Pull request by thedava**
Added no-cache metatags to disable the browser caching of the html coverage report.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
:-1: Surely you should configure your websever to add these headers if you don't want caching. This now limits people to not having caching.

**Comment by sebastianbergmann** [comment]
Thank you, @GrahamCampbell, for pointing this out. I have reverted the patch.

**Comment by GrahamCampbell** [comment]
:beers:

**Comment by thedava** [comment]
I don't see the point in caching the report data. That is something that constantly changes after every new generation.

**Pull request merged**
